"""followers

Revision ID: 830dbfc63844
Revises: 3de555522350
Create Date: 2021-01-17 21:33:10.262366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830dbfc63844'
down_revision = '3de555522350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
